{% set name = "tf-models-official" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  # url: https://github.com/tensorflow/models/archive/v1.13.0.tar.gz
  # url: https://files.pythonhosted.org/packages/fd/f0/b255a0c227fe7d9b1e90dd234eb4832048fb8b5ed356514481bd23169ec2/tf-models-official-2.6.0.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95454a9a6c369c77dd2b5a23f37ede21fea59ca0b7e9e2a8cac62acb7e67bd3e

build:
  number: 0
  skip: True  # [win]  # Skip all windows for now due to numpy/scipy version pinning issues


requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
    - protobuf
  run:
    - python
    - tensorflow >=1.12.0
    - numpy >=1.16.1
    - protobuf >=3.0.0


test:
  imports:
    # From tensorflow-feedstock:
    # "Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    # Also skip on OSX due to OSX version requirements, see
    # https://github.com/conda-forge/tensorflow-feedstock/pull/62"
    - tf_object_detection  # [win]
  requires:
    - tensorflow
    - cython

about:
  home: https://github.com/tensorflow/models/tree/master/research/object_detection
  license: Apache 2.0
  license_file: LICENSE
  summary: 'As an open source framework to to construct, train and deploy object detection models'

  description: |
    The TensorFlow Object Detection API is an open source
    framework built on top of TensorFlow that makes it easy
    to construct, train and deploy object detection models


extra:
  recipe-maintainers:
    - mxr-conda
    - adbeda
    - oblute
    - rluria14
