{% set name = "tf_object_detection" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/tensorflow/models/archive/v1.13.0.tar.gz
  sha256: 9e762d306888b2bf611a45153a30062d2f40f3afa677df9a6e93efe7bd483832

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
    - protobuf
  run:
    - python >=3.6
    - tensorflow >=1.12.0
    - numpy >=1.16.1
    - protobuf >=3.0.0


test:
  imports:
    - tf_object_detection
  requires:
    - cython

about:
  home: https://github.com/tensorflow/models/tree/master/research/object_detection
  license: Apache-2.0
  license_file: LICENSE
  summary: 'As an open source framework to to construct, train and deploy object detection models'
  description: |
    The TensorFlow Object Detection API is an open source
    framework built on top of TensorFlow that makes it easy
    to construct, train and deploy object detection models

extra:
  recipe-maintainers:
    - mxr-conda
    - dsangillo
